--[[ Exemple :
    antiFreeCam = true  -> Ban and log 
    antiFreeCam = false -> kick and log 
    antiFreeCam = nil   -> disable
]]--


tAD = {}

--#[[ FreeCam ]]#--

tAD.whiteListedCamCoords = {
    {x = 18.09, y = -1121.29, z = 28.91, maxDistance = 10}

}

--#[[ Textures ]]#--

tAD.blackListedTextures = {
    'fm',
    'rampage_tr_main',
    'MenyooExtras',
    'shopui_title_graphics_franklin',
    'deadline',
    'mpleaderboard',
    'digitaloverlay',
    'mpmissmarkers256',
    'elicopterhud',
    'deadline',
    'rampage_tr_main', 
    'mpleaderboard',   
    'cross',
    'mpinventory',   
    'mpmissionend',
    'mpsrange',  
    'trafficcam',
    'mpweaponscommon',   
    'visualflow',
    'mptattoos',   
    'mpweaponsgang1',
    'mphud',   
    'mpweaponsunusedfornow',
    'digitaloverlay',
    'setMenuProperty',
    'bobylebg',
    'mpmissmarkers256',
    'titleBackgroundSprite.dict',
    'titleBackgroundSprite',
    'meow',
    'meow2',  
    'shopui_title_graphics_franklin',
    'gradient_nav',
    'rk36Zr2W8ONhMfo7UavTQ.dict',
    'rk36Zr2W8ONhMfo7UavTQ.text',
    'leaderboard_car_colour_bg',
    'gradient_bgd',
    'titleBackgroundSprite.name',
    'textureDict',
    'textureName',
    'txtRatio',
    'screenX',
    'screenY',
    'heisthud',
    'main_gradient',
    'interaction_bgd',
    'leaderboard_players_icon',
    'mparrow',
    'mp_alerttriangle',
    'pilotschool',
    'hudarrow',
    'arrowright',
    'JTD.dict',
    'JTD.text',
    'arrowleft',
    '0xE7FFAE5EBF23D890',
    'ISMMENU',
    'ISMMENUHeader',
    'ISMMENULogo',
    'shop_box_tick',
    'shop_box_blank',
    'corona_shade',
    'timerbar_sr',
    'timer_cross',
    'timer_tick',
    'header',
    'subTitlebackground',
    'bottomsubTitlebackground',
    'subTitleText',
    'self_pedchanger',
    'veh_nextsprite',
    'wep_ped',
    'srange_gen',
    'hit_cross',
    '0xE7FFAE5EBF23D890',
    'Invoke',
    'cock_moscow',
    'menu_gif',
    'hud_lock',
    'hud_corner',
    'cockmenuuu',
    'loadhack',
    'mpentry',
    'mp_modenotselected_gradient',
    'shared',
    'menuarrow_32',
    'mp_modeselected_gradient',
    '__REAPER2__',
    '__REAPER3__',
    '__REAPER8__',
    '__REAPER10__',
    '__REAPER6__',
    '__REAPER7__',
    '__REAPER5__',
    'lhs_bg',
    '__REAPER23__',
    '__REAPER24__',
    '__REAPER16__',
    '__REAPER15__',
    'mprankbadge',
    'globe_bg',
    '__REAPER21__',
    '__REAPER22__',
    '__REAPER20__',
    '__REAPER19__',
    '__REAPER18__',
    '__REAPER17__',
    '__REAPER14__',
    '__REAPER13__',
    '__REAPER12__',
    '__REAPER11__',
    '__REAPER9__',
    '__REAPER4__',
    '__REAPER1__',
    'combat_htype',
    '0xE7FFAE5EBF23D890',
    'Invoke',
    'DrawSprite',
    '~g~CockMenu',
    'width',
    'cock_moscow',
    'vertissotraperdamnshit',
    'srange_gen',
    'hit_cross',
    'mpentry',
    'mp_modenotselected_gradient',
    'corona_shade',
    'aim-fov-draw-alpha',
    'mpinvperscommon',
    '__PAPYMENU1__',
    '__PAPYMENU2__',
    '__PAPYMENU3__',
    '__PAPYMENU4__',
    '__PAPYMENU5__',
    '__PAPYMENU6__',
    '__PAPYMENU7__',
    '__PAPYMENU8__',
    '__PAPYMENU9__',
    '__PAPYMENU10__',
    '__PAPYMENU11__',
    '__PAPYMENU12__',
    '__PAPYMENU13__',
    '__PAPYMENU14__',
    '__PAPYMENU15__',
    '__PAPYMENU16__',
    '__PAPYMENU17__',
    '__PAPYMENU18__',
    '__PAPYMENU19__',
    '__PAPYMENU20__',
    '__PAPYMENU21__',
    '__PAPYMENU22__',
    '__PAPYMENU23__',
    '__PAPYMENU22__',
    'wmlua.V.AllDraw',
    'shop_tick_icon',
    'mpinventory',
    'mp_specitem_ped',
    'circle_checkpoints',
    'circle_checkpoints_big',
    'basejumping',
    'ped0',
    '1',
    'ped4',
    'ped3',
    'ped2',
    'ped1',
    '2',
    '3',
    '4',
    'arrow_pointer',
    'checkon',
    'titleBackgroundSprite',
    'lagserveur',
    'Fallout',
    'Fivex',
    'Cobra',
}

--#[[ Trigger ]]#--

tAD.triggerProtection = {
    {event = 'LasVegas:RevivePlayer', stopEulen = true, allowed = {
        ['LasVegas'] = true,
    }},
    {event = 'LasVegasesx:setJob', stopEulen = true, allowed = {
    }},
    {event = 'KiLaF:boutique:requestedData', stopEulen = true, allowed = {
    }},
    {event = 'KiLaF:boutique:setVip', stopEulen = true, allowed = {
    }},
    {event = 'LasVegasesx:spawnVehicle', stopEulen = true, allowed = {
    }},

}

tAD.antiBlackListedTrigger = {
    'esx:getSharedObject',
    'esx:setJob'
}

--#[[ Screen ]]#--

tAD.blackListedScreenWords = {
    'fallout', 'fivex', 'godmode', 'server troll', 'modmenu', 'aimbot', 'spectate', 'cheat', 'lua menu', 'falcon', 'kick player', 'trigger', 'give money',
    'give weapon', 'destroy menu', 'weapon menu', 'explode player', 'give armor', 'semi godmode', 'freeze player', 'kick from vehicle', 'magneto', 'attach ufo',
    'attack building', 'online players options', 'esx money', 'esx boss', 'hydro', 'kill engine', 'kick out of veh', 'aimbo1t', 'kill everyone', 'super jump',
    'free cam', 'object spooner', 'injected at', 'misc options', 'world options', 'teleport options', 'vehicle options', 'self options', 'weapon options',
    'esp', 'blips', 'gamertag', 'repair vehicle', 'customise vehicle', 'power multiplier', 'torque multiplier', 'semi godmode', 'night vision', 'thermal vision',
    'no ragdoll', 'noclip', 'no-clip', 'weapon list', 'get all weapons', 'remove weapon', 'no reload', 'no recoil', 'trigger bot', 'rapid fire', 'force mode', 
    'explosive ammo', 'make all vehicles fly', 'dump', 'lua executor', 'carry everyone', 'spam chat', 'fake message', 'fuck server', 'particle effects', 'freeze server',
    'ism', 'ism menu'
}
